### ISSUE TITLE
Didn't see 14 tests fail after setup

### ISSUE THREAD

**Issue by devinrhode2** [tunein/frontend-challenge-1#2]
Hmm.. here's my full logs, starting with npm install

```
frontend-challenge-1 ➤ npm install                                    git:master
npm WARN package.json javascript-challenge-1@1.0.0 No repository field.
should@7.1.1 node_modules/should
├── should-type@0.2.0
├── should-equal@0.5.0
└── should-format@0.3.1

gulp-mocha@2.2.0 node_modules/gulp-mocha
├── resolve-from@1.0.1
├── through@2.3.8
├── plur@2.1.1 (irregular-plurals@1.1.0)
├── temp@0.8.3 (os-tmpdir@1.0.1, rimraf@2.2.8)
├── mocha@2.3.4 (escape-string-regexp@1.0.2, diff@1.4.0, commander@2.3.0, supports-color@1.2.0, growl@1.8.1, debug@2.2.0, mkdirp@0.5.0, glob@3.2.3, jade@0.26.3)
└── gulp-util@3.0.7 (object-assign@3.0.0, array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, fancy-log@1.1.0, lodash._reescape@3.0.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, replace-ext@0.0.1, minimist@1.2.0, has-gulplog@0.1.0, chalk@1.1.1, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)

gulp@3.9.0 node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── tildify@1.1.2 (os-homedir@1.0.1)
├── semver@4.3.6
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, supports-color@2.0.0, ansi-styles@2.1.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (sequencify@0.0.7, stream-consume@0.1.0, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, findup-sync@0.3.0, resolve@1.1.6)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, defaults@1.0.3, strip-bom@1.0.0, vinyl@0.4.6, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (object-assign@3.0.0, array-differ@1.0.0, array-uniq@1.0.2, lodash._reinterpolate@3.0.0, fancy-log@1.1.0, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, beeper@1.1.0, replace-ext@0.0.1, has-gulplog@0.1.0, vinyl@0.5.3, gulplog@1.0.0, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
frontend-challenge-1 ➤ gulp                                           git:master
zsh: command not found: gulp
frontend-challenge-1 ➤ npm $ npm install --global gulp                git:master

[redacted noise #lol]

frontend-challenge-1 ➤ npm install --global gulp                      git:master
/Users/drhode/.nvm/versions/node/v4.1.2/bin/gulp -> /Users/drhode/.nvm/versions/node/v4.1.2/lib/node_modules/gulp/bin/gulp.js
gulp@3.9.0 /Users/drhode/.nvm/versions/node/v4.1.2/lib/node_modules/gulp
├── interpret@0.6.6
├── pretty-hrtime@1.0.1
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.2.0
├── semver@4.3.6
├── tildify@1.1.2 (os-homedir@1.0.1)
├── v8flags@2.0.10 (user-home@1.1.1)
├── chalk@1.1.1 (escape-string-regexp@1.0.3, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.1.5)
├── liftoff@2.2.0 (extend@2.0.1, rechoir@0.6.2, flagged-respawn@0.3.1, resolve@1.1.6, findup-sync@0.3.0)
├── vinyl-fs@0.3.14 (graceful-fs@3.0.8, strip-bom@1.0.0, vinyl@0.4.6, defaults@1.0.3, mkdirp@0.5.1, through2@0.6.5, glob-stream@3.1.18, glob-watcher@0.0.6)
└── gulp-util@3.0.7 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reescape@3.0.0, lodash._reevaluate@3.0.0, fancy-log@1.1.0, beeper@1.1.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, replace-ext@0.0.1, has-gulplog@0.1.0, gulplog@1.0.0, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.12)
frontend-challenge-1 ➤ gulp watch                                     git:master
[18:40:49] Using gulpfile ~/repos/frontend-challenge-1/gulpfile.js
[18:40:49] Starting 'test'...
[18:40:49] Starting 'watch-and-test'...
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
[18:40:49] Finished 'watch-and-test' after 602 ms
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
2015-12-17 18:40 gulp[6790] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch EMFILE
    at exports._errnoException (util.js:849:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1222:26)
frontend-challenge-1 ➤                                                 
```

**Comment by devinrhode2** [comment]
here's the colorized result:
![screen shot 2015-12-17 at 6 45 44 pm](https://cloud.githubusercontent.com/assets/539816/11888003/321cf7b2-a4ee-11e5-9d19-86dd26950dc3.png)

Wow github has drag and drop down.

**Comment by devinrhode2** [comment]
..reading the gulpfile, I see it's just a mocha test suite, so I'll just run mocha directly. I see the 14 tests failing. Not blocked ;)

**Comment by devinrhode2** [comment]
Ah.. all the tests failed with `TypeError: cannot read property 'eql' of undefined` because without gulp the `should` module doesn't get injected. Seems to just add some methods to native objects prototype style, and indeed just adding `var should = require('should')` to the top of the first test file fixed this. Now I'm pretty certain have the intended failures

**Comment by andozw** [comment]
I will take a look tomorrow. Thanks Devin!
